// Two-pass build.
//
// The transform needs the browser-side host runtime as a *string* (it writes it
// to disk as `myst-anywidget-static-host.mjs` and prepends it into each per-widget
// wrapper module). But we author that runtime as real, type-checked TypeScript in
// `src/runtime/`. This script reconciles the two:
//
//   1. Bundle `src/runtime/index.ts` to a single ESM string (browser target).
//   2. Emit `src/generated/runtime-source.ts` exporting that string as RUNTIME_SOURCE.
//   3. Bundle `src/plugin.ts` (which imports the generated module) to `dist/plugin.mjs`.
//
// `src/generated/` is a derived artifact and is gitignored — never edit it by hand.

import { build } from "esbuild";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

async function bundleRuntimeToString() {
  const result = await build({
    entryPoints: [path.join(root, "src/runtime/index.ts")],
    bundle: true,
    write: false,
    format: "esm",
    platform: "browser",
    target: "es2020",
  });
  return result.outputFiles[0].text;
}

function writeGeneratedModule(runtimeSource) {
  const generatedDir = path.join(root, "src/generated");
  fs.mkdirSync(generatedDir, { recursive: true });
  const out = path.join(generatedDir, "runtime-source.ts");
  const contents =
    "// AUTO-GENERATED by scripts/build.mjs — do not edit.\n" +
    "// The browser host runtime (src/runtime/*) bundled to a string.\n" +
    `export const RUNTIME_SOURCE = ${JSON.stringify(runtimeSource)};\n`;
  fs.writeFileSync(out, contents);
  return out;
}

async function bundlePlugin() {
  await build({
    entryPoints: [path.join(root, "src/plugin.ts")],
    bundle: true,
    format: "esm",
    platform: "node",
    target: "es2022",
    outfile: path.join(root, "dist/plugin.mjs"),
  });
}

async function main() {
  const runtimeSource = await bundleRuntimeToString();
  writeGeneratedModule(runtimeSource);
  await bundlePlugin();
  console.log("[build] wrote dist/plugin.mjs");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
